<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    
    <PackageId>FlowOnRails</PackageId>
    <Version>0.1.0</Version>
    <Authors>alguem5381</Authors>
    <Description>A modern, lightweight, and compiler-safe library for Railway Oriented Programming in C#.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>rop railway-oriented-programming functional result csharp error-handling monad</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/Alguem5381/FlowOnRails</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\"/>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FlowOnRails.Tests" />
  </ItemGroup>

</Project>
